name: Automatic Releases

env:
  TZ: Asia/Shanghai

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: echo "date=$(date +'%Y-%m-%d')"  >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: false
          tag_name: ${{ env.date }}
          name: ${{ env.date }}
