name: Automatic Releases
# 自动发布CDN内容
on:
  
  # 可以手动执行
  workflow_dispatch:
  
  # push到master分支时执行
  push:
    branches:
    - master
    - main
    
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: "redcrazyghost/CDN@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          Automatic_release_tag: "${{ steps.date.outputs.date }}"
          draft: "Automatic Releases"
          prerelease: false
          files: |
            *
    
        
        
     
