name: Automatic Releases
# 自动发布CDN内容
on:
  # 可以手动执行
  workflow_dispatch:
  
  # push到master分支时执行
  push:
    tags:
      - '*'
    branches:
    - master
    - main
    
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: false
          tag_name: ${{steps.previous_tag.outputs.tag}}
