name: Automatic Releases
# 自动发布CDN内容
on:
  
  # 可以手动执行
  workflow_dispatch:
  
  # push到master分支时执行
  push:
    branches:
    - master
    - main
    
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          files: ./**
          tag_name: 'latest'
          name: 'latest'
        
    
        
        
     
