name: Automatic Releases
# 自动发布CDN内容
on:
  # 可以手动执行
  workflow_dispatch:
  
  # push到master分支时执行
  push:
    tags:
      - '*'
    branches:
    - master
    - main
    
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    # 参数date
      - id: date
        run: echo "date=$(date +'%Y-%m-%d')"  >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: false
          tag_name: ${{ env.date }}
          name: ${{ env.date }}
